### ISSUE TITLE
Kafka Consumer not working on multiple sessions

### ISSUE THREAD

**Issue by cdel2** [HiromuHota/pentaho-kettle#110]
The error comes when I try to get records from stream in PDI with Kafka Consumer while different users are accessing the webspoon instance. 

## Expected Behavior
Kafka Consumer step consumes Kafka topic properly and the Get Records from Stream step in the "T_STREAM_JOB_GENERAL" transformation fetches the messages from the topic consumed.

## Actual Behavior
07-Aug-2018 12:48:05.509 WARNING [RxCachedThreadScheduler-1] org.pentaho.osgi.kettle.repository.locator.impl.spoon.SpoonRepositoryProvider.getRepository Invalid thread access
2018/08/07 12:48:05 - T_STREAM_JOB_GENERAL - Dispatching started for transformation [T_STREAM_JOB_GENERAL]
2018/08/07 12:48:05 - Get records from stream.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
2018/08/07 12:48:05 - JSON Input.0 - Finished processing (I=1, O=0, R=1, W=1, U=0, E=0)
2018/08/07 12:48:05 - Text file output.0 - Finished processing (I=0, O=1, R=1, W=1, U=0, E=0)
07-Aug-2018 12:48:05.598 WARNING [T_STREAM_JOB_GENERAL - Text file output] org.pentaho.osgi.kettle.repository.locator.impl.spoon.SpoonRepositoryProvider.getRepository Invalid thread access

## Steps to Reproduce the Problem
  1. Create a Kafka Consumer step in webspoon
  2. Create a Get Records from Stream step in another transformation
  3. Use the webspoon instance on different machines

### Server
  - webSpoon(latest)
  - Docker(latest)
  - Kafka Consumer uses a direct connection to Kafka bootstrap server.

### Client

**Comment by HiromuHota** [comment]
Thanks for reporting this issue. I was able to reproduce it.
My observations are:
1. Kafka Consumer only works on one user session (more precisely on one running Transformation) at a time.
1. Kafka Consumer in the Transformation that starts most earliest among others only works. In other words, the first one takes and exclusively uses it. If the first one finishes, the second one can take it.

My hunch is that there is a singleton around Kafka consumer (and producer too) that can be used by one Transformation at a time.
Please bear with it until it is fixed.

**Comment by HiromuHota** [comment]
I realized that this issue port had two different issues:
1. "Invalid thread access" error at `SpoonRepositoryProvider.getRepository` (resolved by 5d364b5)
2. Only one Kafka Consumer consumes a Kafka topic at a time.

According to [The Kafka Docs](https://kafka.apache.org/documentation/#intro_consumers), the latter is not an issue.

> The way consumption is implemented in Kafka is by dividing up the partitions in the log over the consumer instances so that each instance is the exclusive consumer of a "fair share" of partitions at any point in time.

Unless a topic has two or more partitions, one consumer exclusively consumes the topic.
I hope this helps you, @cdel2, but please reopen this if your topic has more partitions than consumers and still having an issue.
