### ISSUE TITLE
Why the dialog can not show totally when I create a new database connection to oracle

### ISSUE THREAD

**Issue by shashaaixinpei** [HiromuHota/pentaho-kettle#111]
Hi everyone, I have a question about the webspoon. 

When I use a computure which screen size is 14-inch  try to create a new database connection to oracle, the dialog can not show totally, as the follow picture shows
![1](https://user-images.githubusercontent.com/24243518/45157154-d9523900-b212-11e8-8715-a74b66d4dc35.jpg)
The options “User Name” and "Password" can not show,but I can see them when I change a lager screen with 21-inch, like this
![2022524030](https://user-images.githubusercontent.com/24243518/45157621-431f1280-b214-11e8-8150-2d458346392e.jpg)

 I hope you can help me!! 
 Thanks a lot

### Server
  - OS :  CentOS7.4
  - Java : JDK 1.8
  - Servlet container : Apache Tomcat 8.5.23
  - webSpoon :version 0.8.1.0

### Client
  -
  - Browser : Google Chrome 64.0.3282.140)

**Comment by HiromuHota** [comment]
Please use the browser’s zoom-out (ctrl and -)
This is the best practice I can think of
https://support.google.com/chrome/answer/96810?hl=en


________________________________

**Comment by shashaaixinpei** [comment]
Thank you! Maybe a drop-down control can be set here and it will more user friendly, like this 
![default](https://user-images.githubusercontent.com/24243518/45292784-ce581b00-b528-11e8-936f-183c38f4f8d7.PNG)

**Comment by HiromuHota** [comment]
Thanks for your suggestion, but unfortunately I cannot see a drop-down in the image you attached.
You probably uploaded a different image.
