### ISSUE TITLE
I can't connect to a repository

### ISSUE THREAD

**Issue by nsoria1** [HiromuHota/pentaho-kettle#114]
## Expected Behavior
I would like to connect to a repository but the web interface is shown grey and non-clickable.

Alternatively, I've tried to connect to my local transformation with docker without success. 

## Actual Behavior
![screen shot 2018-09-11 at 11 46 38](https://user-images.githubusercontent.com/32987417/45367814-75d05e80-b5b8-11e8-80d8-444b087aadf0.png)
This is how it looks for me.

## Steps to Reproduce the Problem

  1. No step to reproduce the problem, just trying to connect to a database repository.

### Server
  - OS (e.g., Mac OS X 10.12.6): AWS AMI (Centos 7)
  - Java (e.g., Oracle JDK 8u151): java version "1.8.0_181"
                                                        Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
                                                        Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
  - Servlet container (e.g., Apache Tomcat 8.5.20): Apache Tomcat/8.5.33
  - webSpoon (e.g., version: 0.8.0.13 or commitId: 0211d84b): Latest

### Client
  - OS (e.g., Mac OS X 10.12.6): Mac OS X
  - Browser (e.g., Google Chrome 64.0.3282.140): Google Chrome.

Thank you very much!

**Comment by HiromuHota** [comment]
I believe this is a bug of Spoon itself (not of webSpoon) as you can see other bug reports like [this](https://community.hitachivantara.com/thread/14145-pdi-81-missing-connect-button).
A workaround is the same as on Spoon: delete the Karaf cache and restart the container.
Specifically,
```
$ docker exec -it container-name rm -rf /usr/local/tomcat/system/karaf/caches/webspoonservletcontextlistener
$ docker restart container-name
```
Hope this helps.

**Comment by nsoria1** [comment]
Apologizes since the docker issue may need to be created on a different issue.
I've installed WebSpoon without docker and I'm seeing this issue.

The docker issue, is that I can't access host files.

**Comment by HiromuHota** [comment]
The original issue can be resolve by `rm -rf $CATALINA_HOME/system/karaf/caches/webspoonservletcontextlistener` and restart the Tomcat.

The Docker issue.. is not actually an issue. Docker container is isolated from the host and has its own file system. Please treat it as an external server.
Having said, you can mount files from the host to the container so that the container can see them as local files.
Alternatively, you can use repositories, which you originally tried.

**Comment by HiromuHota** [comment]
I don't think rebooting the server would resolve the issue.
Can you find any error message in log files (ie `$CATALINA_HOME/logs/catalina.out`)?

**Comment by nsoria1** [comment]
[catalina output.log](https://github.com/HiromuHota/pentaho-kettle/files/2379423/catalina.output.log)

I particullary do not see anything strange on the log mentioned by you. I don't know if there is another logging file where should I check.

As a workaround, I've run the docker version with all plugins and I was able to connect to database repository. Also I've shared a folder from host so I can open ktr and xml files. 
The only issue that I faced with this approach is that I can't execute shells scripts on host since it uses root user.

**Comment by HiromuHota** [comment]
Based on your log file, I suspect that the current directory when starting Tomcat is not at `$CATALINA_HOME` (in your case `/opt/tomcat`).
[This](https://github.com/HiromuHota/pentaho-kettle/issues/84) reports a similar issue.

**Comment by HiromuHota** [comment]
Can you tell me how you start Tomcat and what is the current directory when you do it?
I usually use the following command. As you can see, the current directory is `/Users/hiromu/Downloads/apache-tomcat-8.5.34` when I start Tomcat.
```
My-MBP:~ hiromu$ cd /Users/hiromu/Downloads/apache-tomcat-8.5.34
My-MBP:apache-tomcat-8.5.34 hiromu$ pwd
/Users/hiromu/Downloads/apache-tomcat-8.5.34
My-MBP:apache-tomcat-8.5.34 hiromu$ ./bin/startup.sh
```

**Comment by nsoria1** [comment]
I'm starting tomcat with the startup.sh script.
It is located on a different path for me (/opt/tomcat/system/karaf/etc/startup.properties)

I'm not sure if this is wrong but tomcat's $CATALINA_HOME path is /opt/tomcat/.

I will read the similar issue and try to follow what was useful for the issue op, since I've installed tomcat manually. Maybe I need to uninstall it and install it through yum.

Thank you!

**Comment by HiromuHota** [comment]
> I'm starting tomcat with the startup.sh script.

Please execute the startup.sh from /opt/tomcat, specifically,
```
$ cd /opt/tomcat
$ ./bin/startup.sh
```

> It is located on a different path for me (/opt/tomcat/system/karaf/etc/startup.properties)

I believe this is a typo. The `startup.sh` is located at `/opt/tomcat/bin`. Correct me if I'm wrong.

> $CATALINA_HOME path is /opt/tomcat/

This is totally fine.

**Comment by nsoria1** [comment]
I've started the tomcat server as you mentioned, here is the output:

> ec2-user@Superset-DEV /opt/tomcat/bin$cd /opt/tomcat
> ec2-user@Superset-DEV /opt/tomcat$./bin/startup.sh
> Using CATALINA_BASE:   /opt/tomcat/
> Using CATALINA_HOME:   /opt/tomcat/
> Using CATALINA_TMPDIR: /opt/tomcat//temp
> Using JRE_HOME:        /usr
> Using CLASSPATH:       /opt/tomcat//bin/bootstrap.jar:/opt/tomcat//bin/tomcat-juli.jar
> Tomcat started.

Yes, my previous comment has a typo, I'm sorry. The startup.sh is located in the /opt/tomcat/bin folder. Still without any success.

**Comment by HiromuHota** [comment]
If this does not work, I have no idea.
Let me try to reproduce your issue. To do this, can you tell me which AMI you are using?

**Comment by nsoria1** [comment]
It's the AMI 2 (Amazon Linux 2).

Here are the [steps](https://www.rosehosting.com/blog/install-tomcat-9-on-centos-7/) that I've followed to install Apache Tomcat on the AMI 2 machine.

It probably has to do with the way that I've installed it.

**Comment by HiromuHota** [comment]
Sorry I couldn't reproduce your problem. No problem occurred.
For your information, here are the steps I've taken.

I used Vagrant to deploy the Amazon Linux 2 by

```
My-MBP:amazonlinux2 hiromu$ vagrant init winky/amazonlinux-2   --box-version 1.0
```

Executed the following commands to install Java, Tomcat, and webSpoon.
The full history of commands can be found here [history.txt](https://github.com/HiromuHota/pentaho-kettle/files/2398715/history.txt).

```
    2  sudo yum -y update
    4  sudo yum install java-1.8.0-openjdk.x86_64
   10  wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.33/bin/apache-tomcat-8.5.33.tar.gz
   18  cd /opt/
   21  sudo tar -xvf ~/apache-tomcat-8.5.33.tar.gz 
   26  sudo mv apache-tomcat-8.5.33 tomcat
   28  echo "export CATALINA_HOME='/opt/tomcat/'" >> ~/.bashrc
   29  source ~/.bashrc
   31  sudo useradd -r tomcat --shell /bin/false
   32  sudo chown -R tomcat:tomcat /opt/tomcat/
   44  sudo chown -R vagrant:vagrant /opt/tomcat/
   50  cd /opt/tomcat/
   52  unzip /vagrant/pdi-ce-8.1.0.0-365.zip 
   54  mv data-integration/system ./
   55  mv data-integration/plugins ./
   56  wget wget https://raw.githubusercontent.com/HiromuHota/webspoon-docker/0.8.1.16/install.sh
   58  chmod +x install.sh 
   59  export version=0.8.1.16
   60  export dist=8.1.0.0-365
   61  ./install.sh 
   63  ./bin/startup.sh 
```

Following [the instructions](https://www.rosehosting.com/blog/install-tomcat-9-on-centos-7/), I tried to launch Tomcat by user `tomcat` first, but actually did it by user `vagrant` instead. Just because this is how I start Tomcat usually.


Here is the log output.
[catalina.out.txt](https://github.com/HiromuHota/pentaho-kettle/files/2398704/catalina.out.txt)

**Comment by HiromuHota** [comment]
Close this due to inactivity. Feel free to reopen if you encounter this issue.
