### ISSUE TITLE
Carte initial page not showing up

### ISSUE THREAD

**Issue by mattcasters** [HiromuHota/pentaho-kettle#118]
## Expected Behavior
Going to http://<hostname>:8080/spoon/kettle I expect the traditional welcome page.

## Actual Behavior
500 Error and stack trace:

java.lang.NullPointerException
	org.pentaho.di.www.CarteServlet.doGet(CarteServlet.java:74)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

## Steps to Reproduce the Problem
Start webspoon and visit the URL  http://<hostname>:8080/spoon/kettle

### Server
  - Latest webspoon in docker

**Comment by HiromuHota** [comment]
Is this initial page still available in the community edition, say 8.1?

**Comment by mattcasters** [comment]
Thanks for looking into this.  It's unfortunately not the only thing that got broken.
