### ISSUE TITLE
Data Grid Step - Tab key not usable within data grid table.  Skips to Okay button.

### ISSUE THREAD

**Issue by usbrandon** [HiromuHota/pentaho-kettle#123]
## Expected Behavior
PDI has a lot of tabular input boxes, like in the data grid step.  Clicking on a row and being able to hit tab to have it move the cursor to the next column makes ktr creation much quicker.

## Actual Behavior
Instead of the Tab key moving to the next column inside a table, it moves focus to the next entire UI element on screen, like an Okay button, Cancel, Title input etc.  It treats the whole table as a whole component.

**Comment by HiromuHota** [comment]
Thank you for reporting. I acknowledged this issue.

My initial investigation found that the tab key to move cells is achieved by https://github.com/pentaho/pentaho-kettle/blob/master/ui/src/main/java/org/pentaho/di/ui/core/widget/TableView.java#L1092-L1095.
I thought it was an easy fix by adding support for TAB key as I did for ESC key [here](https://github.com/HiromuHota/rap/commit/facb83c78c21438d6e8f15ea0f8293a9a8449cf5) but this did not work.
I need to investigate more.

**Comment by HiromuHota** [comment]
Now I see why this issue happens.

According to [RAP developer guide](https://www.eclipse.org/rap/developers-guide/devguide.php?topic=key-and-mouse-events.html),
> Traverse events are fired before a key event, and only for keys that can change the focus. (For example Escape, Tab, Arrows.) The idea is that you can prevent or manipulate the focus change, but that is not supported in RWT.

> The KeyEvent object has a doit field (as do untyped events), which is true by default. In SWT, this field can be set to false to prevent the default operation associated with pressing or releasing this key, like inserting a character in a Text widget. RAP supported this in a limited capacity until 1.4, but support was discontinued in 1.5.

A traverse event is supposed to be cancelled as written in [here](https://github.com/pentaho/pentaho-kettle/blob/master/ui/src/main/java/org/pentaho/di/ui/core/widget/TableView.java#L1226-L1231).
This cancellation works on Spoon (SWT) but not on webSpoon (RAP/RWT).
When the traverse event is not cancelled, the focus moves to the next widget, ie OK button.
