### ISSUE TITLE
Need clarification on Pan and Kitchen

### ISSUE THREAD

**Issue by GirishAthanikar** [HiromuHota/pentaho-kettle#143]
Hi Team,
I am able to run my transformation job (.ktr) using AEL (Hadoop Cluster) in webspoon.

**Question:** 
How to run Pan and Kitchen using AEL.?

**Comment by HiromuHota** [comment]
webSpoon does not include Pan and Kitchen but include Carte.
You can use Carte to run ktr/kjb. See this [video](https://www.youtube.com/watch?v=__5meQPAVT0&t=4s).
