### ISSUE TITLE
WebSpoon does not show the run options for server or cluster.

### ISSUE THREAD

**Issue by DataClubs** [HiromuHota/pentaho-kettle#161]
WebSpoon does not show the run options for server or cluster.

At first, I should admit WebSpoon is really what I dream!  Thanks a lot.

I can not find  run options with run with remote server, or clusters.  but according to the 11th PPT in 
https://www.slideshare.net/HiromuHota/handson-demo-of-pdi-using-webspoon, webspoon has the function. By the way, I have use the Spoon for many years.

the version i build with docker is 0.8.2.18 , and my environments are:
  - OS (e.g., Mac OS X 10.12.3):
  - Browser (e.g., Google Chrome & Safari)

Thanks again.

**Comment by HiromuHota** [comment]
Seems like you figured it out on your own, but for those who have the same question, I'll post my answer below.

Pentaho introduced the concept of "Run Configuration" at 7.1 before when the slide deck was created. http://pedroalves-bi.blogspot.com/2017/05/pentaho-7.1.html
By default, only a Run Configuration for local is available.
You have to manually create a Run Configuration for a remote server and/or clusters.
