### ISSUE TITLE
i cant't use connect

### ISSUE THREAD

**Issue by javacodeofmy** [HiromuHota/pentaho-kettle#163]
## Expected Behavior
![image](https://user-images.githubusercontent.com/7877585/60696045-99351300-9f16-11e9-9964-c76cc0cf4252.png)
i have this problem please help me think you very much

## Actual Behavior
Screenshots and error messages are helpful.

## Steps to Reproduce the Problem

  1.
  1.
  1.

### Server
  - OS (e.g., windows10):
  - Java (e.g., Oracle JDK 8u151):
  - Servlet container (e.g., Apache Tomcat 8.5.42):
  - webSpoon (e.g., version: 0.8.0.13 or commitId: 0211d84b):

### Client
  - OS (e.g., windows10):
  - Browser (e.g., Google Chrome 64.0.3282.140):

**Comment by HiromuHota** [comment]
It looks like the reverse proxy is not working.

Please let me know how you deployed webSpoon.
- Did you use the Docker version?
- If you did not use the Docker version, did you follow the instructions at https://github.com/HiromuHota/pentaho-kettle#without-docker?

**Comment by javacodeofmy** [comment]
Thank you for having solved the Thank God project.
