### ISSUE TITLE
Where is org.eclipse.swt.widgets.UploadDialog and org.eclipse.swt.widgets.IFileDialog ?

### ISSUE THREAD

**Issue by sywh1234-git** [HiromuHota/pentaho-kettle#170]
Dear:
    When I get the source code of webspoon 8.3.0-371, I can't find the org. Eclipse SWT. Widgets. IFileDialog and org. Eclipse SWT. Widgets. UploadDialog, please tell me where are they?

In addition, the org.eclipse.swt package was a bit of a mess, and I struggled to resolve the conflict, but ended up with two classes that I couldn't find: IFileDialog and UploadDialog.

What should I do?
![image](https://user-images.githubusercontent.com/45229537/62273104-501da380-b46f-11e9-89df-c81dbf346d61.png)

**Comment by HiromuHota** [comment]
They are in org.eclipse.rap.filedialog-XXX.jar (see [here](https://github.com/HiromuHota/pentaho-kettle/wiki/Dev%3A-FileDialog-and-DirectoryDialog)).
This org.eclipse.rap.filedialog-XXX.jar has been customized for webSpoon so please build the customized one (see [here](https://github.com/HiromuHota/pentaho-kettle#build-and-locally-publish-dependent-libraries)).
