### ISSUE TITLE
pentaho-kettle-webspoon-8.3\plugins\repositories\core\pom.xml Change webspoon.version 8.2.0.0-342-18 to 8.3.0.0-371

### ISSUE THREAD

**Issue by sywh1234-git** [HiromuHota/pentaho-kettle#171]
I used pentaho kettle-webspoon 8.3, and then I use maven clean build but it failed because the version 8.2.0.0-342-18 did not exist in the repository，and then I modified two version Numbers in in the files \plugins\repositories\core\pom.xml and plugins\file-open-save\core\pom.xml
,I changed 
<webspoon.version>8.2.0.0-342-18</webspoon.version> 
to
<webspoon.version>8.3.0.0-371</webspoon.version>
, is there any problem?

**Comment by HiromuHota** [comment]
Thanks for finding this issue.
The version should be 8.3.0.0-371-19 instead of 8.3.0.0-371.

Best,
Hiromu

**Comment by sywh1234-git** [comment]
Thank you very much ! 
And I have another trouble than how can I create a respository use webspoon
