### ISSUE TITLE
Wiki Doc question

### ISSUE THREAD

**Issue by yuanxuzhang** [HiromuHota/pentaho-kettle#177]
Question about Wiki >>Admin: Security >> Steps and job entries restriction  [Steps and job entries restriction](https://github.com/HiromuHota/pentaho-kettle/wiki/Admin%3A-Security#steps-and-job-entries-restriction)
It seems do not work, until I done the following steps:
1. append the file name with "alternative"(like kettle-steps-alternative.xml).
2. move them to CATALINA_HOME/bin(default CATALINA_HOME is tomcat base dir).

**Comment by HiromuHota** [comment]
Thank you for your question.

The first step is partially correct. These xml files should be renamed. If not, kettle-job-entries.xml or kettle-steps.xml inside the `kettle-engine-VERSION.jar` will be used.
https://help.pentaho.com/Documentation/6.1/0R0/0V0/010/000

The second step, I still have to check it.

**Comment by HiromuHota** [comment]
I checked the second step.
`$CATALINA_HOME` worked but `$CATALINA_HOME/bin` did not work for me.

**Comment by HiromuHota** [comment]
I think it depends on what path is included in the class path.
If you are at `$CATALINA_HOME` and start Tomcat by `bin/startup.sh`, `$CATALINA_HOME` will be included in the class path. Same thing to `$CATALINA_HOME/bin`.

**Comment by yuanxuzhang** [comment]
Totally agree with you, thanks.
