### ISSUE TITLE
Ability to hide the whole menubar

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#178]
## Expected Behavior

This is requested by @yuanxuzhang at #96,
> I want to embed webspoon in a iframe. It satisfies the needs without menubar,and what's more, the whole page layout looks better.

## Actual Behavior

Currently, it is not possible to hide the entire menubar (File, Edit, View, Action, etc.).

**Comment by HiromuHota** [comment]
@yuanxuzhang Now MainToolbar and MenuBar can be hidden.
Please try and let me know if this change satisfies you.

**Comment by yuanxuzhang** [comment]
That is what i want。thanks
tip：
If the **rap -branch** update to 3.9.0 ,[build-and-locally-publish-dependent-libraries](https://github.com/HiromuHota/pentaho-kettle#build-and-locally-publish-dependent-libraries)， the build work will be more smoothly.

**Comment by HiromuHota** [comment]
Thank you for letting me know this.
I corrected the README.
