### ISSUE TITLE
”UISessionImpl“ was removed from session when refresh the Browser

### ISSUE THREAD

**Issue by jerchen-ui** [HiromuHota/pentaho-kettle#180]
hi：
I was realizing connecting to the repository automatically. but when i refresh the browser, the connecting statemenet was dispaired because  the ”UISessionImpl“ was removed from session when refresh the Browser. how to avoid this ? please kindly reply，thanks

**Comment by HiromuHota** [comment]
Hi, thanks for asking!
I'd like to better understand the issue.
Can you take a snapshot of the error and/or tell me how to reproduce the error?

**Comment by HiromuHota** [comment]
Close due to inactivity.
Maybe duplicate of #181 .
