### ISSUE TITLE
Refresh Browser Repositories Status Loss

### ISSUE THREAD

**Issue by zhangrenhua** [HiromuHota/pentaho-kettle#181]
Hello, I found that the repositories login status lost after the browser refresh reload, how can I handle the repositories login status?

**Comment by HiromuHota** [comment]
Page reload of webSpoon is equivalent to App restart of Spoon.
This means the connected repository is lost when you reload webSpoon.

One possible workaround is to check `Launch connection on startup` like below.
This will allow you to automatically connect to the repository on the page reload.
<img width="629" alt="Screen Shot 2019-09-26 at 10 40 58 AM" src="https://user-images.githubusercontent.com/20668349/65711727-6187c400-e04a-11e9-8367-e1392b357243.png">

**Comment by zhangrenhua** [comment]
okay, thank you!
