### ISSUE TITLE
how to add custom plugin

### ISSUE THREAD

**Issue by cmdares** [HiromuHota/pentaho-kettle#189]
there has some opensource plugins in the markplace，how to intergrate with webspoon？
Do you need to modify the plugin code again? If so, please demonstrate a simple custom plugin
thanks！regard！

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HiromuHota** [comment]
See https://github.com/HiromuHota/pentaho-kettle/blob/webspoon-8.3/README.md#third-party-plugins-and-jdbc-drivers
If things do not work (this happens when a plugin is not compatible with webSpoon), please let me know.
