### ISSUE TITLE
url params to open a trans

### ISSUE THREAD

**Issue by cmdares** [HiromuHota/pentaho-kettle#193]
Can I directly open the trans or jobs in the page by URL  parameters
like:  http://localhost:8080/spoon/spoon/?repo=my_repo&trans=trans003.ktr
thanks.

**Comment by HiromuHota** [comment]
See [here](https://github.com/HiromuHota/pentaho-kettle/wiki/User%3A-Query-parameters-for-File-open) and let me know if it works.
