### ISSUE TITLE
file: readme.md , description error

### ISSUE THREAD

**Issue by lucienhsu** [HiromuHota/pentaho-kettle#195]
> (https://github.com/HiromuHota/pentaho-kettle#rap)
> > $ git clone -b webspoon-3.11.0 https://github.com/HiromuHota/rap.git
$ cd rap
$ mvn clean install

Shoud be 'webspoon-9.0' ?

**Comment by lucienhsu** [comment]
my mistake, sorry.

**Comment by HiromuHota** [comment]
At least I updated the branch from webspoon-3.11.0 to webspoon-3.12.0.
Thank you.
