### ISSUE TITLE
external ldap auth provider

### ISSUE THREAD

**Issue by gebele** [HiromuHota/pentaho-kettle#201]
## Expected Behavior
That it works

## Actual Behavior
Doesn't work

## Steps to Reproduce the Problem
Set URL to external provider

Did you ever testet this feature ?

**Comment by HiromuHota** [comment]
I tested when I introduced this feature.
I tested again today and confirmed that it worked in my environment/setting.
I appreciate that you've reported an issue and would appreciate more if you could do so more nicely.

A snippet of my `WEB-INF/spring/security.xml`:
```
  <ldap-server url="ldap://host.docker.internal:389/dc=example,dc=org" manager-dn="cn=admin,dc=example,dc=org" manager-password="admin" />
  <authentication-manager>
    <ldap-authentication-provider
      user-dn-pattern="uid={0},ou=people"
      group-search-base="ou=groups"
      group-role-attribute="cn"
      group-search-filter="uniqueMember={0}"
    />
  </authentication-manager>
```

My test ldap server is deployed as a docker (using https://github.com/osixia/docker-openldap) and accessible at `host.docker.internal:389`.
An exported ldif is like https://github.com/HiromuHota/pentaho-kettle/blob/3a5cf0a4d2b3a731edc3cfad392df8398c345900/assemblies/pdi-ce/src/main/resources/example.ldif.

Please let me know how to reproduce this issue.
For example, I need snippets of `WEB-INF/web.xml` and `WEB-INF/spring/security.xml`.
In addition, I need these information.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

### Server
  - OS (e.g., Mac OS X 10.12.6):
  - Java (e.g., Oracle JDK 8u151):
  - Servlet container (e.g., Apache Tomcat 8.5.20):
  - webSpoon (e.g., version: 0.8.0.13 or commitId: 0211d84b):

### Client
  - OS (e.g., Mac OS X 10.12.6):
  - Browser (e.g., Google Chrome 64.0.3282.140):

**Comment by gebele** [comment]
Thanks for your quick reply !
I'm using your webspoon docker image and followed your scenario with the openldap image but I can't get it to work. ldapsearch does work from inside the webspoon container to the ldap container but if I set the URL/IP in the security.xml I see nothing happening in the ldap container log ?

**Comment by HiromuHota** [comment]
Did you restart the webSpoon container after changing the security.xml?

If things work correctly, you should be able to see some log messages in the ldap container.

**Comment by gebele** [comment]
Yes I restarted several times. Today I tried again and now I see it - strange ?! thx
