### ISSUE TITLE
Connect to Reprository  or marketplace Error: Operation "call" on target "w586" of type "rwt.widgets.Browser" failed:

### ISSUE THREAD

**Issue by penske-boranna** [HiromuHota/pentaho-kettle#202]
## Expected Behavior
Connect to Reprository  or marketplace 

## Actual Behavior
Screenshots and error messages are helpful.
![image](https://user-images.githubusercontent.com/38040898/80249734-feb5e400-868f-11ea-8685-e0b65d267c25.png)

Client Error
Details
Error: Error: Operation "call" on target "w586" of type "rwt.widgets.Browser" failed:
SecurityRestriction:
Browser-Widget can not access "127.0.0.1:9051" from "34.93.149.87:8080".
Properties: 
functions = genericFunction,openURL

  Script: {"head":{},"operations":[["destroy","w255"],["destroy","w559"],["destroy","w561"],["destroy","w563"],["destroy","w564"],["destroy","w565"],["destroy","w566"],["destroy","w567"],["destroy","w568"],["destroy","w569"],["destroy","w570"],["destroy","w571"],["destroy","w572"],["destroy","w573"],["destroy","w574"],["destroy","w575"],["destroy","w576"],["destroy","w577"],["destroy","w578"],["destroy","w579"],["destroy","w580"],["destroy","w581"],["destroy","w582"],["destroy","w558"],["set","w2",{"text":"Spoon - Marketplace"}],["set","w17",{"bounds":[0,0,2048,25]}],["set","w25",{"enabled":false}],["set","w27",{"enabled":false}],["set","w28",{"enabled":false}],["set","w29",{"enabled":false}],["set","w37",{"enabled":false}],["set","w38",{"enabled":false}],["set","w44",{"enabled":false}],["set","w45",{"enabled":false}],["set","w51",{"enabled":false}],["set","w54",{"enabled":false}],["set","w55",{"enabled":false}],["set","w56",{"enabled":false}],["set","w57",{"enabled":false}],["set","w58",{"enabled":false}],["set","w59",{"enabled":false}],["set","w60",{"enabled":false}],["set","w61",{"enabled":false}],["set","w62",{"enabled":false}],["set","w63",{"enabled":false}],["set","w64",{"enabled":false}],["set","w65",{"enabled":false}],["set","w22",{"enabled":false}],["set","w33",{"enabled":false}],["set","w34",{"enabled":false}],["set","w67",{"enabled":false}],["set","w71",{"enabled":false}],["set","w79",{"enabled":false}],["set","w80",{"enabled":false}],["set","w204",{"enabled":false}],["set","w7",{"enabled":false}],["set","w8",{"enabled":false}],["set","w125",{"itemCount":2,"itemMetrics":[[0,0,167,0,24,30,129]]}],["create","w587","rwt.widgets.GridItem",{"parent":"w125","index":0,"texts":["Transformations"],"images":[["rwt-resources/generated/393e560b.png",24,24]]}],["create","w588","rwt.widgets.GridItem",{"parent":"w125","index":1,"texts":["Jobs"],"images":[["rwt-resources/generated/393e560b.png",24,24]]}],["set","w127",{"itemCount":0,"itemMetrics":[[0,0,0,0,24,30,0]]}],["set","w198",{"visibility":false}],["set","w121",{"children":["w123","w207","w585"],"tabHeight":33,"selection":"w589"}],["set","w199",{"bounds":[0,0,153,34]}],["set","w526",{"bounds":[153,0,204,34]}],["create","w589","rwt.widgets.CTabItem",{"parent":"w121","index":2,"style":["CLOSE"],"bounds":[357,0,180,34],"font":[["Verdana","Lucida Sans","Arial","Helvetica","sans-serif"],14,false,false],"text":"Marketplace","image":["rwt-resources/generated/605a7178.png",16,16],"showClose":true}],["set","w123",{"bounds":[3,37,1660,912],"clientArea":[0,0,1660,912]}],["set","w124",{"bounds":[0,2,1660,910]}],["set","w207",{"bounds":[3,37,1660,912],"visibility":false,"clientArea":[0,0,1660,912]}],["set","w222",{"bounds":[0,34,1660,878],"clientArea":[0,0,1660,878]}],["set","w223",{"bounds":[0,0,1660,878],"clientArea":[0,0,1660,878]}],["set","w224",{"bounds":[0,0,1660,878]}],["set","w225",{"bounds":[0,0,1660,878],"clientArea":[0,0,1658,876]}],["call","w225.gc","init",{"x":0,"y":0,"width":1658,"height":876,"font":[["Verdana","Lucida Sans","Arial","Helvetica","sans-serif"],14,false,false],"fillStyle":[255,255,255,255],"strokeStyle":[74,74,74,255]}],["call","w225.gc","draw",{"operations":[["setTransform",1,0,0,1,0,0],["beginPath"],["rect",0,0,1658,876],["fill"],["setTransform",1,0,0,1,0,0],["strokeStyle",[61,99,128,255]],["font",[["Verdana","Lucida Sans","Arial","Helvetica","sans-serif"],17,false,false]],["drawImage","rwt-resources/generated/c5f5be95.png",629,238]]}],["create","w585","rwt.widgets.Composite",{"parent":"w121","style":["NONE"],"children":["w586"],"bounds":[3,37,1660,912],"background":[0,0,0,0],"clientArea":[0,0,1660,912]}],["create","w586","rwt.widgets.Browser",{"parent":"w585","style":["NONE"],"children":[],"bounds":[0,2,1660,910],"tabIndex":35,"background":[0,0,0,0],"url":"http://127.0.0.1:9051/@pentaho/marketplace@9.0.0.0-423/main.html"}],["call","w586","createFunctions",{"functions":["genericFunction","openURL"]}],["call","rwt.client.JavaScriptExecutor","execute",{"content":"try{rap.getObject( 'w587' ).$el.attr( 'test-id', 'view_Transformations' );}catch(e){}"}],["call","rwt.client.TextSizeMeasurement","measureItems",{"items":[["t-385701006","Marketplace",["Verdana","Lucida Sans","Arial","Helvetica","sans-serif"],14,false,false,-1,false],["t-385701005","Marketplace",["Verdana","Lucida Sans","Arial","Helvetica","sans-serif"],14,false,false,-1,false]]}]]}
  Stack: Error: Operation "call" on target "w586" of type "rwt.widgets.Browser" failed:
SecurityRestriction:
Browser-Widget can not access "127.0.0.1:9051" from "34.93.149.87:8080".
Properties: 
functions = genericFunction,openURL

    at Object._processError (http://34.93.149.87:8080/spoon/rwt-resources/3110/rap-client.js:226:3814)
    at Object.processOperationArray (http://34.93.149.87:8080/spoon/rwt-resources/3110/rap-client.js:226:924)
    at Object.processMessage (http://34.93.149.87:8080/spoon/rwt-resources/3110/rap-client.js:226:253)
    at Object._handleSuccess (http://34.93.149.87:8080/spoon/rwt-resources/3110/rap-client.js:230:3439)
    at rwt.remote.Request._success (http://34.93.149.87:8080/spoon/rwt-resources/3110/rap-client.js:98:925)
    at rwt.remote.Request._onReadyStateChange (http://34.93.149.87:8080/spoon/rwt-resources/3110/rap-client.js:98:1596)
    at XMLHttpRequest. (http://34.93.149.87:8080/spoon/rwt-resources/3110/rap-client.js:7:219)
  Debug: off
  Request: {"head":{"requestCounter":13},"operations":[["notify","w85","Selection",{"button":1,"shiftKey":false,"ctrlKey":false,"altKey":false}],["notify","w15","Hide",{}],["set","w1",{"cursorLocation":[280,205]}]]}

## Steps to Reproduce the Problem

   Try to resolve https://github.com/HiromuHota/webspoon-docker/issues/35

### Server
  - OS (e.g., Mac OS X 10.12.6): Cent OS 7
  - Java (e.g., Oracle JDK 8u151):  openjdk version "1.8.0_242"
  - Servlet container (e.g., Apache Tomcat 8.5.20):  Tomcat/8.5.23
  - webSpoon (e.g., version: 0.8.0.13 or commitId: 0211d84b): version=0.9.0.21 and dist=9.0.0.0-423

### Client
  - OS (e.g., Mac OS X 10.12.6):  windows10 
  - Browser (e.g., Google Chrome 64.0.3282.140): Google Chrome

[catalina.2020-04-24.log](https://github.com/HiromuHota/pentaho-kettle/files/4531218/catalina.2020-04-24.log)
[karaf.log](https://github.com/HiromuHota/pentaho-kettle/files/4531219/karaf.log)
[localhost.2020-04-24.log](https://github.com/HiromuHota/pentaho-kettle/files/4531220/localhost.2020-04-24.log)
[localhost_access_log.2020-04-24.txt](https://github.com/HiromuHota/pentaho-kettle/files/4531221/localhost_access_log.2020-04-24.txt)
[spoon.log](https://github.com/HiromuHota/pentaho-kettle/files/4531222/spoon.log)

**Comment by HiromuHota** [comment]
Looks like some of the plugins are not replaced with patched ones.

According to https://github.com/HiromuHota/webspoon-docker/issues/35#issuecomment-619207161, you skipped some of the steps.
Please follow each and every step in https://github.com/HiromuHota/pentaho-kettle#without-docker.
For example, "Run install.sh at $CATALINA_HOME" step replaces plugins with patched ones.

**Comment by HiromuHota** [comment]
Also remember to remove the Karaf cache `rm -rf system/karaf/caches/` before you start Tomcat.

**Comment by penske-boranna** [comment]
Executed Run install.sh and issue got resolved.
