### ISSUE TITLE
Look and feel changes do not affect the ui

### ISSUE THREAD

**Issue by gurumark** [HiromuHota/pentaho-kettle#204]
## Expected Behavior
I want to disable tooltips which has no effect. 

## Actual Behavior
The display tooltip checkbox has no effect on the actual behavior.

## Steps to Reproduce the Problem

I disabled the tooltips (help and others) from the Look and Feel menu under Options and restarted the app. This is a big issue specifically when editing SQL since the tooltip pops up showing the code in a tooltip window, blocking the code editor. And then the step icon gets stuck and moves with the mouse cursor when I canceled out of the step editor.

### Server
  - Ubuntu 18.04
  - The latest docker container available
### Client
  - Ubuntu 18.04
  -Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by gurumark** [comment]
I experience this issue with the icons only. The others seem to be working just fine.

**Comment by HiromuHota** [comment]
I'm trying to understand the issue. Can you take a screenshot and upload it here?

**Comment by gurumark** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/1859151/81115914-7f77aa00-8ef2-11ea-92a6-27b5bb72588c.png)

Here it shows the tooltip blocking the SQL window. I disabled the tooltip but did not work.
Thank you.

**Comment by HiromuHota** [comment]
I see. Still I cannot reproduce the tooltip itself. Maybe because I use Mac and you use Ubuntu.
How do you activate the tooltip? Hover the mouse cursor over the sql? Or click somewhere?

**Comment by gurumark** [comment]
I hover over the SQL. As long as it is close enough to the left edge it covers the area. Then the table input icon gets stuck. I can that out of the way by esc key. But the tooltip is very annoying. Is there any way I can disable the whole tooltip. Look and feel does not work.

**Comment by HiromuHota** [comment]
I think the inability to disable the tooltip is a bug. Once I can reproduce it, I’ll start fixing it. Please bear with me for a while.

**Comment by HiromuHota** [comment]
Is the "Replace variables in script?" option enabled?

**Comment by HiromuHota** [comment]
Okay, I'm seeing the tooltip now even on mac.

**Comment by HiromuHota** [comment]
Somehow related: https://jira.pentaho.com/browse/PDI-13242

**Comment by HiromuHota** [comment]
I tracked it down and found that this tooltip had been introduced by fca7e265ea5ee6945ceba2329fb7d7c9b2439146.
So this tooltip is displayed only if the "Replace variables in script?" option enabled to show an sql with variables replaced.
This means that "Replace variables in script?" option needs to be disabled to get rid of the tooltip (after disabling it, close the dialog and open it again to make it effective).

**Comment by gurumark** [comment]
Yes, it was enabled. I turned it off and the tooltip is gone. Thank you!
Were you able to track down the icon getting stuck?
1= Double click the table input icon
2- Click OK or Cancel
3- The table input icon is stuck to the mouse cursor.
4- Press ESC to release it and the text on the canvas disappears.
5- Click on anywhere on the canvas and the text appears again.

**Comment by HiromuHota** [comment]
Does this issue only happen with the table input or happen with any other step?

**Comment by gurumark** [comment]
It happens in every step. It makes the tool unusable. I think there is a missing event listener. When I clicked on the step and then get out, it still thinks and I am still on the canvas. It pulls the icon wherever the mouse cursor goes.

**Comment by gurumark** [comment]
I think it is also related "Replace variables in script?" as well. I don't click on the checkbox but it assumes that I clicked.

**Comment by HiromuHota** [comment]
I've been aware of the fact that a step can be sticky (to the cursor), especially when your cursor moves fast and/or the server is slow.
Let me see what I can do.

Regarding the checkbox being clicked, I've never experienced this. Can you upload a video to demonstrate it (mask any confidential part)? Does this happen always/sometimes on any browser/os?

**Comment by gurumark** [comment]
I think "Replace variables in script?" issue was on me. I cannot reproduce it.

**Comment by HiromuHota** [comment]
How about the sticky step? Is this so critical on other browser/os?

**Comment by gurumark** [comment]
I could not reproduce the sticky issue on Firefox/Ubuntu 18.04. The UI does not look not nice though - colors off and cannot set the colors for the ui.
Another issue with chrome is "I could not load another job from the same repository". It give dabase communication errors. Using Firefox, I could not reproduce this issue. It loaded the second job without any issues.

**Comment by gurumark** [comment]
I've found that if you disable "Use OS look", it starts the sticky icon thing on Firefox as well. I think if you open too many tabs on Chrome, it cannot load multiple transformations or jobs: loses connection to the database. It is weird.

**Comment by HiromuHota** [comment]
Regarding the database/repository connection issue, are you using a database type of a repository? If so, how many tabs were concurrently connected to the repository when the “I could not load another job from the same repository” error happened?

By the way, I couldn’t find any information when I googled “I could not load another job from the same repository”. Where did this show up? In a browser tab, browser console, or server logs?

**Comment by gurumark** [comment]
I am using a database repository. Here is the error I got:
************
Error connecting to database: (using class org.gjt.mm.mysql.Driver)
yesterday at 2:57 PM 2020/05/07 14:57:58 - org.pentaho.di.trans.steps.databaselookup.DatabaseLookupMeta@d26e9f9 - Communications link failure
yesterday at 2:57 PM 2020/05/07 14:57:58 - org.pentaho.di.trans.steps.databaselookup.DatabaseLookupMeta@d26e9f9 -
yesterday at 2:57 PM 2020/05/07 14:57:58 - org.pentaho.di.trans.steps.databaselookup.DatabaseLookupMeta@d26e9f9 - The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
yesterday at 2:57 PM 2020/05/07 14:57:58 - org.pentaho.di.trans.steps.databaselookup.DatabaseLookupMeta@d26e9f9 - ERROR (version 9.0.0.0-423-21, build 9.0.0.0-423-21 from 2020-02-07 06.11.21 by jenkins) : An error occurred:
yesterday at 2:57 PM 2020/05/07 14:57:58 - org.pentaho.di.trans.steps.databaselookup.DatabaseLookupMeta@d26e9f9 - Error occurred while trying to connect to the database
*******************
I was trying to open another job. The dialog box was frozen and noticed the error above. I had 10-15 chrome tabs open. I had only one spoon tab. Immediately, I tried opening the same 2 jobs on Firefox and it worked.

**Comment by HiromuHota** [comment]
Thank you for the log messages, which sounds to me like a database was sluggish for a moment.
Unfortunately, there is hardly anything I can do for this database repository issue.

**Comment by gurumark** [comment]
I don't think that's the case. My server has more than enough power. Besides, I tested on Firefox which worked and then ran it on Chrome. I think there is an issue related to chrome memory management which is nothing to do with this tool.
Firefox is working for me which is fine but it does not show the colors. I would recommend checking out the sticky icon issue though since it is chrome.

**Comment by HiromuHota** [comment]
Can you upload a screen shot that demonstrates the "colors off and cannot set the colors for the ui" issue?

Also I've checked the sticky icon both a local webspoon and a remote one (on AWS), but it happened only when the mouse cursor moved really fast and couldn't find it so critical in my environment.
As there is a chance that we are talking about similar but different issues, I'd appreciate if you could upload a screen recording that demonstrates this sticky icon.

Finally, just to confirm, are the server and the client the same machine?

**Comment by gurumark** [comment]
How can I contact you directly? The video has some production info.

**Comment by HiromuHota** [comment]
Reach me at hiromu.hota@hal.hitachi.com

**Comment by gurumark** [comment]
I sent you an email yesterday. I hope you were able to get it.
