### ISSUE TITLE
in docker carte can't connect database repsitory

### ISSUE THREAD

**Issue by jiangpan** [HiromuHota/pentaho-kettle#206]
## screen capture in docker

![](https://pic-1300675853.cos.ap-shanghai.myqcloud.com/picgo/20200525152237.png)

![](https://pic-1300675853.cos.ap-shanghai.myqcloud.com/picgo/20200525152441.png)

## Steps to Reproduce the Problem

  1. i make dir $CATALINA_HOME/system/kettle/ and copy  slave-server-config.xml to the dir 

  1. config repository

  1. carte can't connect to repository

#### If deployed as a Docker container
  - docker tag hiromuhota/webspoon:0.7.1.13-full

### Client
  - OS windows 10 1909
  - Browser google chrome  83.0.4103.61 (Official Build) (64-bit)

**Comment by jiangpan** [comment]
any could help me

**Comment by HiromuHota** [comment]
0.8.0.13 and earlier, Carte was not configurable (#90).
Please use 0.8.0.14 or later if you want to configure Carte by `slave-server-config.xml`.
