### ISSUE TITLE
Could you share on the wiki how to deploy Web Spoon in a production environment, architecture example etc.

### ISSUE THREAD

**Issue by fgomezotero** [HiromuHota/pentaho-kettle#210]
Hello, I am looking to implement Web Spoon in the production environment as part of the data analysis platform.
So if you could share any reference of how to do it I will be so thankful.

Regards.

**Comment by HiromuHota** [comment]
The following blog describes a production deployment and its architecture.
Hope this helps.
https://community.hitachivantara.com/s/article/webspoon-is-now-in-production
