### ISSUE TITLE
How do you config others vfs schemes likes webdav, https to be used in transformations?

### ISSUE THREAD

**Issue by fgomezotero** [HiromuHota/pentaho-kettle#214]
Hello,

I am interested in configuring other vfs schemes to be able to connect to different data sources such as webdav, http (s), (s) ftp, etc.

Using the visual connection manager vfs only allows us to connect to the local disk, Hadoop cluster, S3 and HDFS, but for many cases of ETL's these sources are insufficient.

If you could provide an example and give us some reference on how to configure another schema vfs like webdav I would be very grateful to you.

Regards.

**Comment by HiromuHota** [comment]
Hi @fgomezotero ,

Thank you for using webSpoon.
As of v9.0, PDI supports only a limited file system types like S3, HDFS, Google Drive.
https://help.pentaho.com/Documentation/9.0/Products/Connecting_to_Virtual_File_Systems

As webSpoon just provides a web GUI, additional vfs or anything beyond what PDI offers is out of scope of webSpoon.
If you want PDI to support additional vfs, please create an issue at [Pentaho Jira](https://jira.pentaho.com/secure/Dashboard.jspa).

Thank you for your understanding.

**Comment by hansva** [comment]
To add a bit more context:
Inside steps you can still use other VFS connection types.

for example if you want to read a csv directly from ftp you can use a text file input and in the filepath you can use ftp://myusername:mypassword@somehost/pub/downloads/somefile.txt

You just can't browse there using the vfs browser.

There is still the option to create some global parameters that contain a source. you could add MY_FTP_SERVER to the Kettle.properties and bind this paramter to  "ftp://myusername:mypassword@somehost"  
and in the text file input step you can then do ${MY_FTP_SERVER}/path/to/file.csv

**Comment by HiromuHota** [comment]
@hansva thanks for clarification. I was confused between vfs as a data source and vfs browser.

I was actually able to use SFTP in webSpoon as described at https://github.com/HiromuHota/pentaho-kettle/wiki/Admin%3A-Security#restrict-access-to-the-local-files-and-use-files-in-a-file-server-instead
> In addition, it is recommended to use files in a file server such as SFTP for data inputs/outputs. You can use VFS to access those files. There are many supported file systems: SFTP, HTTPS, WebDAV; and some of them have a user authentication mechanism.

@fgomezotero, as @hansva describes, you should be able to use those vfs (like SFTP) by manually typing the url like below:

![image](https://user-images.githubusercontent.com/20668349/89056259-99b5fe00-d310-11ea-965d-04509a80080b.png)

or you can use a global parameter as @hansva describes.

I'd recommend to try it on Spoon first then switch to webSpoon.
