### ISSUE TITLE
how can i set the result-area's logs font color red to find out whats the errors in logs?

### ISSUE THREAD

**Issue by finch-xu** [HiromuHota/pentaho-kettle#215]
## Checklist before submitting an issue

- [x] This issue does not happen on Spoon.  
If your issue happens on Spoon too, it originates from Spoon (not from webSpoon). Please look at [Pentaho Community Forums](https://forums.pentaho.com/), or seek help at [Hitachi Vantara Community](https://community.hitachivantara.com/s/pentaho), or submit an issue at [Pentaho JIRA](https://jira.pentaho.com/projects/PDI)).
- [x] I searched for existing issues at [here](https://github.com/HiromuHota/pentaho-kettle/issues) and [there](https://github.com/HiromuHota/webspoon-docker/issues).

## Expected Behavior
kettle's error font is red in result area, but this webkettle is not , they are all black font  in result , and i cant't find the errors quickly. is there a button or settings in webkettle to change this ? thank u :) 

## Actual Behavior
Screenshots and error messages are helpful.

## Steps to Reproduce the Problem

  1. run a trans or a job
  2. if there is a bug in this trans or just fail to finash
  3. in the result area ,the logs font is not red, all logs is the same black font

#### If deployed as a Docker container
  - Docker 19

#### Else
  - webSpoon lastest

### Client
  - docker 19
  - Microsoft Edge 84.0.522.52 (with chromium)

**Comment by HiromuHota** [comment]
Hi @finch-xu , thank you for your feedback.
Currently, it is not possible to change font color in the log.
Spoon uses `StyledText` but webSpoon uses `Text`, which does not allow change colors of text, as RAP/RWT has not implemented `StyledText`.
Unfortunately, I don't have a plan to fix this in a foreseeable future, but would welcome your pull-request.
