### ISSUE TITLE
Failed to build rap

### ISSUE THREAD

**Issue by luohao110** [HiromuHota/pentaho-kettle#216]
I did the following and failed   
$ git clone -b webspoon-3.12.0 https://github.com/HiromuHota/rap.git
$ cd rap
$ mvn clean install

![微信图片_20200901143944](https://user-images.githubusercontent.com/48583201/91810742-00586f80-ec61-11ea-8aba-0f50843bfdb4.png)

**Comment by luohao110** [comment]
It's the windows 10

**Comment by hansva** [comment]
I am afraid it will be windows or your maven version causing the issue.
but you can also find these artifacts in following location:
https://artifactory.project-hop.org/ui/repos/tree/General/hop-snapshots-local%2Forg%2Feclipse%2Frap

**Comment by HiromuHota** [comment]
@luohao110 according to the error message, no git repository was found in your working directory.
Please check if you have `.git` directory at `D:\project_test\libraries\rap\.git`.

As @hansva mentioned, if you just need Jar files, you can download them at the url he mentioned.

**Comment by luohao110** [comment]
thanks
