### ISSUE TITLE
Failed to build webspoon-9.0

### ISSUE THREAD

**Issue by WEIHUWEIHU** [HiromuHota/pentaho-kettle#222]
## Actual Behavior
[INFO] Reactor Summary:
[INFO]
[INFO] Pentaho Data Integration 9.0.0.0-423 ............... SUCCESS [ 13.283 s]
[INFO] PDI Core 9.0.0.0-423-22 ............................ SUCCESS [ 44.793 s]
[INFO] webSpoon Security 9.0.0.0-423-22 ................... SUCCESS [  3.197 s]
[INFO] PDI Engine 9.0.0.0-423-22 .......................... SUCCESS [02:49 min]
[INFO] PDI User Interface 9.0.0.0-423-22 .................. SUCCESS [02:44 min]
[INFO] PDI File Open and Save Plugin Core ................. SUCCESS [ 50.840 s]
[INFO] PDI File Open and Save New Plugin Core ............. SUCCESS [ 53.575 s]
[INFO] PDI Get Fields Plugin Core ......................... SUCCESS [ 47.416 s]
[INFO] PDI Repositories Plugin Core ....................... SUCCESS [01:06 min]
[INFO] PDI Engine Configuration Plugin UI ................. SUCCESS [  6.989 s]
[INFO] Connections Plugin UI .............................. SUCCESS [ 41.183 s]
[INFO] PDI Plugins ........................................ SUCCESS [  0.143 s]
[INFO] PDI Assemblies ..................................... SUCCESS [  0.099 s]
[INFO] PDI Client Static Assets 9.0.0.0-423-22 ............ SUCCESS [  1.951 s]
[INFO] PDI Client Libraries 9.0.0.0-423-22 ................ FAILURE [  5.441 s]
[INFO] PDI Client Community Edition 9.0.0.0-423-22 ........ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:17 min
[INFO] Finished at: 2020-11-12T16:45:48+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pdi-libs: Could not resolve dependenci                                                                                                                es for project org.pentaho.di:pdi-libs:pom:9.0.0.0-423-22: Failed to collect dep                                                                                                                endencies at org.pentaho:pentaho-hadoop-shims-common-mapreduce:jar:9.0.2020.02.0                                                                                                                0-423: Failed to read artifact descriptor for org.pentaho:pentaho-hadoop-shims-c                                                                                                                ommon-mapreduce:jar:9.0.2020.02.00-423: Could not find artifact org.pentaho:pent                                                                                                                aho-ce-jar-parent-pom:pom:9.0.0.2-521 in pentaho-public (https://repo.orl.eng.hi                                                                                                                tachivantara.com/artifactory/pnt-mvn/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit                                                                                                                ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea                                                                                                                d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso                                                                                                                lutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pdi-libs

## Steps to Reproduce the Problem

  1.In the outset, "PDI Repositories Plugin Core" failed to build
 [ERROR] Failed to execute goal on project repositories-plugin-core: Could not re                                                                                                                solve dependencies for project org.pentaho.di.plugins:repositories-plugin-core:b                                                                                                                undle:9.0.0.0-423: Could not find artifact pentaho-kettle:kettle-core:jar:9.0.0.                                                                                                                0-423-21 in pentaho-public (https://repo.orl.eng.hitachivantara.com/artifactory/                                                                                                                pnt-mvn/) -> [Help 1]

  2.I alter the plugins/repositories/core/pom.xml <webspoon.version>9.0.0.0-423-21</webspoon.version> -> 9.0.0.0-423-22 to build "PDI Repositories Plugin Core" succeed . But  "PDI Client Libraries 9.0.0.0-423-22"  failed to build

#### Else
  - windows 10:
  - openjdk 1.8.0_242:
  - webSpoon 9.0:

**Comment by HiromuHota** [comment]
@WEIHUWEIHU Thank you for reporting the issue.
I updated the outdated version at `plugins/repositories/core/pom.xml` and was able to build it as of today.
Please try again.

**Comment by WEIHUWEIHU** [comment]
@HiromuHota 
Thank you very much for your reply.I tried again,the problem has been solved.
