### ISSUE TITLE
edit job graph occur Browser-Widget can not access "127.0.0.1:9051" from "localhost:8080"

### ISSUE THREAD

**Issue by fantasyWJP** [HiromuHota/pentaho-kettle#223]
![image](https://user-images.githubusercontent.com/47958519/103194582-12020900-491b-11eb-9397-78d15d22b65b.png)
when i click browse,sth is wrong:(system/karaf/etc/org.pentaho.requirejs.cfg file content is set:context.root=/spoon/osgi)

Error: Error: Operation "call" on target "w901" of type "rwt.widgets.Browser" failed:
SecurityRestriction:
Browser-Widget can not access "127.0.0.1:9051" from "localhost:8080".
Properties: 
functions = getConnectionId,close,select,help

  Script: {"head":{},"operations":[["set","w17",{"bounds":[0,0,1920,25]}],["create","w900","rwt.widgets.Shell",{"style":["CLOSE","MAX","RESIZE","TITLE","APPLICATION_MODAL","BORDER"],"parentShell":"w2"}],["listen","w900",{"Move":true,"Resize":true,"Activate":true,"Close":true}],["set","w900",{"image":["rwt-resources/generated/605a7178.png",16,16],"text":"Select a File","active":true,"minimumSize":[545,458],"activeControl":"w901","children":["w901"],"bounds":[486,155,947,626],"visibility":true}],["listen","w900",{"Traverse":true}],["create","w901","rwt.widgets.Browser",{"parent":"w900","style":["NONE"],"children":[],"bounds":[0,38,945,586],"tabIndex":1,"url":"http://127.0.0.1:9051/@pentaho/di-plugin-file-open-save-new@9.0.0.0-423/index.html#/selectFile?path=%252Fstudy%252Fkettle%252FHiromuHota%252Fapache-tomcat-8.5.60&provider=repository&providerFilter=repository&filter=KTR%2CXML%2CALL&defaultFilter=KTR&origin=spoon"}],["call","w901","createFunctions",{"functions":["getConnectionId","close","select","help"]}],["set","w1",{"focusControl":"w901"}],["set","rwt.client.ServerPush",{"active":true}]]}
  Stack: Error: Operation "call" on target "w901" of type "rwt.widgets.Browser" failed:
SecurityRestriction:
Browser-Widget can not access "127.0.0.1:9051" from "localhost:8080".
Properties: 
functions = getConnectionId,close,select,help

    at Object._processError (http://localhost:8080/spoon/rwt-resources/3120/rap-client.js:226:3814)
    at Object.processOperationArray (http://localhost:8080/spoon/rwt-resources/3120/rap-client.js:226:924)
    at Object.processMessage (http://localhost:8080/spoon/rwt-resources/3120/rap-client.js:226:253)
    at Object._handleSuccess (http://localhost:8080/spoon/rwt-resources/3120/rap-client.js:230:3677)
    at rwt.remote.Request._success (http://localhost:8080/spoon/rwt-resources/3120/rap-client.js:98:925)
    at rwt.remote.Request._onReadyStateChange (http://localhost:8080/spoon/rwt-resources/3120/rap-client.js:98:1596)
    at XMLHttpRequest. (http://localhost:8080/spoon/rwt-resources/3120/rap-client.js:7:219)
  Debug: off
  Request: {"head":{"requestCounter":16},"operations":[["set","w778",{"activeControl":"w788"}],["notify","w788","Selection",{"button":1,"shiftKey":false,"ctrlKey":false,"altKey":false}],["set","w1",{"cursorLocation":[819,192],"focusControl":"w788"}]]}

**Comment by 409201531** [comment]
请问您最后解决了吗

**Comment by 409201531** [comment]
您如何解决的这个 8080访问 9051端口问题，有偿
