### ISSUE TITLE
How run with IntelliJ IDEA in local? Many maven dependencies cannot be downloaded。

### ISSUE THREAD

**Issue by wxdx** [HiromuHota/pentaho-kettle#252]
- OS (Mac OS X 12.3.1):
  - Java (Oracle JDK 11.0.12):
  - Servlet container (Apache Tomcat 8.5.20):
  - webSpoon (version: webpoon-9.0):

### Client
  - OS (Mac OS X 12.3.1):
  - Browser (Google Chrome 101.0.4951.54):

**Comment by wxdx** [comment]
How run with Eclipse in local ? I want to debugger

**Comment by lccoll** [comment]
> How run with Eclipse in local ? I want to debugger

请教下你那边mavern依赖怎么解决的，我这边想本地调试打包
