### ISSUE TITLE
Intalling a plugin

### ISSUE THREAD

**Issue by ankit0611** [HiromuHota/pentaho-kettle#26]
I installed a plugin by copying the plugin jar into 

> tomcat > webapps> spoon > plugin

.
This is a **step plugin** and working fine in desktop application installation. 

Step is not visible in webspoon. Am i missing some configuration? Does webspoon uses ba server installation of data integration?

My installation details:

Version of BA Server EE 6.0.1.0.386
Java version jdk 1.8.0_73
Host OS windows 7 professional 64 bits

**Comment by HiromuHota** [comment]
Hi Ankit,

Please see https://github.com/HiromuHota/pentaho-kettle/blob/webspoon-6.1/README.md#plugins
The easiest way would be putting the step plugin into pentaho-solutions/system/kettle/plugins

Sorry for the confusion, but plugins in the webapps/spoon/plugins are loaded only when it is specified by KETTLE_PLUGIN_BASE_FOLDERS.

**Comment by HiromuHota** [comment]
To avoid unnecessary confusions, I removed the plugins folder from the war file, which will be effective from the next release.
