### ISSUE TITLE
Problem with Menu

### ISSUE THREAD

**Issue by sowe** [HiromuHota/pentaho-kettle#45]
Hi,
When try to access to job , The menu was in a rare position, I attach the screenshot . This test used a docker.

docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

OS information : 4.4.0-57-generic #78~14.04.1-Ubuntu SMP Sat Dec 10 00:14:47 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

![webspoon](https://cloud.githubusercontent.com/assets/482053/25048497/1ba536c6-213d-11e7-916c-3fe0dfc4582d.png)

**Comment by HiromuHota** [comment]
Thanks for reporting! I resolved it in 94f07bff4e1019fc187333a43b9c9530eaa0fd59. This will be included in the next release.

**Comment by HiromuHota** [comment]
As a regression to 94f07bff4e1019fc187333a43b9c9530eaa0fd59, the context menu of Slave server won't pop-up.
![image](https://cloud.githubusercontent.com/assets/20668349/25725458/eda2c4a8-30d4-11e7-8f1c-5e8346fadba4.png)

**Comment by HiromuHota** [comment]
Resolved by 270fe107b8c086cba953596c57e267aa7eaaf583.

**Comment by HiromuHota** [comment]
The context menu of the VFS file chooser is also wrong.

![screen shot 2017-10-12 at 5 47 17 pm](https://user-images.githubusercontent.com/20668349/31525503-91a9ca6e-af75-11e7-9417-c790d611c78e.png)

**Comment by HiromuHota** [comment]
The context menu of the VFS file chooser was resolved by https://github.com/HiromuHota/apache-vfs-browser/commit/043119876fc13de5dfe2e1593fc90708de9ff447.

**Comment by HiromuHota** [comment]
The technical debt has been paid off by HiromuHota/rap@f6528e9eac8e4b5489c569f6a3fe899b97c304b5.
