### ISSUE TITLE
type connection

### ISSUE THREAD

**Issue by sowe** [HiromuHota/pentaho-kettle#47]
Hi ,
I don't see in the menu the possibility to use different type connection (jdbc,odbc and jndi).
![screen shot 2017-04-20 at 10 27 25](https://cloud.githubusercontent.com/assets/482053/25221069/170a86cc-25b4-11e7-9c36-8fe6d9b0fd16.png)

**Comment by HiromuHota** [comment]
This dialog is actually resizable. You can resize it by drag&drop the bottom right corner of the dialog.

**Comment by sowe** [comment]
Yes . is no a bug is only a tip .It's sometimes complicated to resizable the window ...

**Comment by HiromuHota** [comment]
I agree. It is difficult to know if it is resizable or not.
This dialog only has a close button, but not a maximize button. It'd be better to have one.
