### ISSUE TITLE
Please close this issue

### ISSUE THREAD

**Issue by MrMauricioLeite** [HiromuHota/pentaho-kettle#53]
Just wanted to point out that if this is what Pentaho Data Integration is going to be in the future, get ready to a Boom on sales because this is amazing. Really.

Thanks Hiromu for sharing this code online and managing it. I hope Pentaho as a whole move towards this (or at least turn this into a default part of the data-integration product). Kudos.

**Comment by HiromuHota** [comment]
Thanks Mauricio! I will keep trying my best to make this software as good as possible.
