### ISSUE TITLE
File save/open dialog should be like Save As (VFS) / Open URL

### ISSUE THREAD

**Issue by delfer** [HiromuHota/pentaho-kettle#62]
Some steps in Transformations (Microsoft Excel Input, Text File input/output) and Transformation step in Job uses file upload dialog. But it is wrong. They all should use dialog like global Save As (VFS) / Open URL to use files from server. Transfer files between desktop and server is another task outside of this project (it can be NFS, Samba, ftp, web ant other).

**Comment by HiromuHota** [comment]
I totally agree with you.
Please allow me some more time to fix this.

**Comment by HiromuHota** [comment]
Recents commits from f065c063f34b56b825195e1d8b75d0ee385f0865 to cc2b693ec755f1a46aa97f43c82ffc5d2a3e9b11 should fix this.
Please keep in mind that there is a change to rap.filedialog too.
