### ISSUE TITLE
Can't copy script from SQL script step

### ISSUE THREAD

**Issue by delfer** [HiromuHota/pentaho-kettle#63]
It is no copy/paste entries in context dialog at SQL editor. Ctrl-V works (paste), but Ctrl-C not (copy).
Windows 10.0 x64 Chrome 58.0.3029.110
![image](https://user-images.githubusercontent.com/3233181/27216236-828a7362-527d-11e7-9a44-958c74cda91e.png)

**Comment by HiromuHota** [comment]
I downloaded a VM image from [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and deployed Windows 10 (x64, Version: 1607, OS Build: 14393.0) to VirtualBox (Host: Mac OS X).
I tested cut/copy/paste on Chrome (58.0.3029.96).
I confirmed that the cut/copy/paste were absent from the context menu, but was able to do all these operations by key shortcuts (Ctrl-X, -C, -V).

Please tell us some more information
- The exact name of the step? I tested "Table input" and "Execute SQL script".
- Did you try Ctrl-X (cut)? If yes, what happened?
- Version of webSpoon and how was it deployed (Docker, put the war file to Apache Tomcat, or something else)?

**Comment by HiromuHota** [comment]
Close for inactivity. Reopen if needed.

**Comment by delfer** [comment]
@HiromuHota 
Paste: both Ctrl-V and Shift-Insert works
Copy: Ctrl-Insert works; Ctrl-C - not
Cut: Ctrl-X works

**Comment by HiromuHota** [comment]
What version of webSpoon are you using?
I am still not able to reproduce this issue (webSpoon: latest (d1171bd6), Chrome 65.0, Win10).
In my case
Paste: both Ctrl-V and Shift-Insert work
Copy: both Ctrl-C and Ctrl-Insert work
Cut: both Ctrl-X and Shift-Del work

**Comment by delfer** [comment]
@HiromuHota, excuse for troubling. It was fixed in be2db0abfc0870fb610ee8aa58b5e1614bb87863

**Comment by HiromuHota** [comment]
Glad to hear that. Thank you for checking that out.
