### ISSUE TITLE
Requires pentaho-xul-swt 7.1.0.0-12-10 but 7.1.0.0-12-9 still in HiromuHota/pentaho-commons-xul 

### ISSUE THREAD

**Issue by delfer** [HiromuHota/pentaho-kettle#65]
Please, push your changes in  HiromuHota/pentaho-commons-xul  to GitHub.

**Comment by HiromuHota** [comment]
Here you go: https://github.com/HiromuHota/pentaho-commons-xul/commit/b12270e50cf60ef88df4c12862d4d2877e37129b
Thanks for reminding me. I forgot to push this.
