### ISSUE TITLE
can't re-run new transformation

### ISSUE THREAD

**Issue by delfer** [HiromuHota/pentaho-kettle#73]
webSpoon  0.7.1.11 commit 9ffaefd8830

1. Create new transformation
2. Add anything
3. Run
4. WebSpoon will ask you to save transformation on clinet-side
5. Run again and webSpoon can't acces file
![image](https://user-images.githubusercontent.com/3233181/28971208-d9303d6e-7933-11e7-92c9-1f0ed29edc98.png)

Posible solution: auto save on server-side

**Comment by HiromuHota** [comment]
Thank you for reporting as it is important for me to understand how webSpoon is used.

The workaround for this issue, as you've noticed, is to save on server-side.
More specifically, please "Save as (VFS)" before running it when not connected a repository AND you create a new trans/job.
This issue has been resolved by 9360c61bfa46fe0bfeb90cfd35f1505b76e69ae0, which will be effective next release.
