### ISSUE TITLE
webspoon integration with iframe

### ISSUE THREAD

**Issue by nazeri84** [HiromuHota/pentaho-kettle#83]
Hi
I have set up the webspoon on a server and also activated user authentication of that and I need to integrate it with another web app that is running via https. For this porpuse I have used iframe and also I set the configuration of tomcat and webspoon to work with https and port 8443.
I can access webspoon via http and also https without any problems, but when I put its link in the iframe tag, it does not work.
I found out that when I disable the user authentication of webspoon, it works correctly, so my problem is about user authentication and working with iframe.
Do you have any idea in this situation?

I would be thankful if you help me.
Thanks.

**Comment by HiromuHota** [comment]
Can you comment out the following three lines in `webapps/spoon/WEB-INF/spring/security.xml` and try again?

```
    <headers>
      <frame-options policy="SAMEORIGIN"/>
    </headers>
```
https://github.com/HiromuHota/pentaho-kettle/blob/webspoon-7.1/assembly/WEB-INF/spring/security.xml#L17-L19

This is the Spring Security option that prevents 'Clickjacking' (see https://docs.spring.io/spring-security/site/docs/current/reference/html/headers.html#headers-frame-options).
With this option enabled, webSpoon can be integrated (as an iframe) only if it is from the same origin (same host and same port).
Thus, another way to fix it is to have your another web app in the same origin.

**Comment by nazeri84** [comment]
actually I removed that lines in security.xml file before, but it did not work.
I should say the main web site that I want to integrate webspoon with that is based on https, is it a matter?

**Comment by HiromuHota** [comment]
I may be wrong, but I don't think https matters here.

I was wrong about the Spring Security setting. You should not have removed these lines.
According to [here](https://docs.spring.io/spring-security/site/docs/current/reference/html/headers.html#headers-frame-options), "By default, Spring Security disables rendering within an iframe."

So those lines should be something like

```
    <headers>
      <frame-options policy="ALLOW-FROM https://example.com/"/>
    </headers>
```

See [there](https://docs.spring.io/spring-security/site/docs/current/reference/html/appendix-namespace.html#nsa-frame-options) for more details.

**Comment by nazeri84** [comment]
Those code lines do not work for me, because as I have found the form of disabling x-frame option is like this:
<frame-options disabled="true">
but another way is that you can disable the the security part in web.xml file and use this part of codes to have user authentication with considering security framework that you want to use.

<authentication-manager>
 <authentication-provider>
  <user-service>
    <user name="user1" password="password1" authorities="ROLE_USER" />
      <user name="user2" password="password2" authorities="ROLE_USER" />
  </user-service>
 </authentication-provider>
</authentication-manager>
anyway thanks for your answers.

**Comment by HiromuHota** [comment]
Thank you for sharing your information.
