### ISSUE TITLE
Copy to/paste from OS clipboard

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pentaho-kettle#97]
## Expected Behavior

Be able to copy/paste between Spoon and webSpoon, and between different browser tabs 

## Actual Behavior

Currently copy/paste is only possible between opened trans/jobs within one browser tab

**Comment by HiromuHota** [comment]
This would be possible using a JavaScript code within RAP's [scripting](https://www.eclipse.org/rap/developers-guide/devguide.php?topic=scripting.html&version=3.3).
The code would include `document.execCommand('cut')` and `document.execCommand('copy')`, which are now supported by most latest browsers.

**Comment by HiromuHota** [comment]
Copy is relatively easy because it is an one-way (server -> client) data transfer.
Specifically, data can be transferred from server to client: Server (Java) --[1]--> Client (JavaScript) --[2]--> Client (DOM) --[3]--> Client (OS clipboard) and the client does not have to notify the server.

Transferring Widget Data in [RWT Scripting](https://www.eclipse.org/rap/developers-guide/devguide.php?topic=scripting.html&version=3.3) for [1]

```
WidgetUtil.registerDataKeys( "foo" );
widget.setData( "foo", "myData" );
```

See above for [2][3].

Cut needs a return-way to remove cut steps/job entries from the canvas. Paste involves an opposite direction one-way.
According to [RWT Scripting](https://www.eclipse.org/rap/developers-guide/devguide.php?topic=scripting.html&version=3.3), 

> Changing the value on the client does not change it on the server. 

Instead of RWT Scripting, we have to use `RemoteObject` in a custom widget for paste and cut, meaning we have to develop a custom widget.

**Comment by HiromuHota** [comment]
See [RAP 2.0 - New and Noteworthy](https://www.eclipse.org/rap/noteworthy/2.0/) for how to use RemoteObject in Custom Widgets.

**Comment by HiromuHota** [comment]
Resolved by be2db0abfc0870fb610ee8aa58b5e1614bb87863.

**Comment by bamaer** [comment]
copy/paste doesn't work (tested in webspoon-8.2 on firefox 66.0.3, chrome 74.0.3729.75) for steps/entries or 'copy selected rows to clipboard' from grids. 
Chrome web console shows:  
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by HiromuHota** [comment]
Thanks for reporting but I couldn't reproduce the issue (I was able to copy/paste steps/job entries) with the following environments:

#### Server
  - webSpoon: Docker hiromuhota/webspoon:0.8.2.18 and hiromuhota/webspoon:nightly

#### Client
  - OS: Mac OS X 10.14.4
  - Browser: Firefox 66.0.3 and Chrome 74.0.3729.75

A similar error message appeared on Chrome console, saying
> [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312

but this only happened when I scrolled some list and not when I did copy/paste.

**Comment by HiromuHota** [comment]
I'd like to know more details to figure out how it happened to you.
1. Are they used to be working and suddenly stop working? If so, when did it happen?
1. What's the OS at the client side?

**Comment by HiromuHota** [comment]
I'd also like to clarify what "'copy selected rows to clipboard' from grids" refers to.

<img width="671" alt="Screen Shot 2019-04-13 at 2 43 23 PM" src="https://user-images.githubusercontent.com/20668349/56085588-bddb8c00-5dfa-11e9-81be-a0fa65025fd0.png">

Do you mean "copy selected lines to clipboard" as shown above?
I tested and confirmed that it did not work. I think this has been just left broken.
I'll make a different ticket for this.

**Comment by HiromuHota** [comment]
This would be useful; https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/.
